### ISSUE TITLE
Traveller makes the scan stop

### ISSUE THREAD

**Issue by Marcusvdgomes** [Andrewthe13th/Inventory_Kamera#107]
Everytime it scans the traveller the character scan ends even if traveller was the first scan.

**Comment by Andrewthe13th** [comment]
can you share the name of your traveller so we can test it.

**Comment by Marcusvdgomes** [comment]
Sure! It's Legretta.

**Comment by Marcusvdgomes** [comment]
Tried scanning her with both GEO and ELECTRO thinking that it could be something about const. but to no avail.

**Comment by Cupcak3** [comment]
Does the error log say anything?

**Comment by GunnerCat** [comment]
i had the same problem aswell, hopefully it would get fixed soon!

**Comment by Marcusvdgomes** [comment]
Nothing shows up on the error log. It just stops the scanning like if it got to the end of the character list.

**Comment by Scoterster86** [comment]
I also have the same issue. If I make the scanner delay 50ms instead of 0 I get this error:

Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207


I also found a temporary "fix" people can use:

**Comment by Cupcak3** [comment]
Interesting fix @Scoterster86 . If you remove that fix can you confirm that your Traveler name can be found in the `Characters` lookup dictionary after it is scanned from the Paimon menu?

**Comment by Scoterster86** [comment]
> Interesting fix @Scoterster86 . If you remove that fix can you confirm that your Traveler name can be found in the `Characters` lookup dictionary after it is scanned from the Paimon menu?

@Cupcak3 Do you mean the json file or a variable during runtime? I'm using the exe (and don't even have a B: drive).. I see my traveler name on the GUI after starting a scan and don't get a message in the log other than the error. I removed the fix and tried the scan again. It still gives the same error as above

**Comment by Cupcak3** [comment]
Hi there. Sorry for coming back to this issue after a long time. Please let us know if these issues have been resolved in releases or pre-releases so that we can close this issue. Thanks!

**Comment by Marcusvdgomes** [comment]
The issue was resolved with the latest release (V1.2). I could import everything (artifacts, weapons and characters) without any problem.
