### ISSUE TITLE
Cannot find Genshin Impact process

### ISSUE THREAD

**Issue by choko314** [Andrewthe13th/Inventory_Kamera#109]
InventoryKamera.Navigation.InitializeProcess(String processName) 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:行号 330
    InventoryKamera.Navigation.Initialize(String processName) 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:行号 35
   InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() 位置 B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:行号 190

**Comment by Cupcak3** [comment]
What is the name of the process in Task Manager? Right now I think we're only looking for the English exe,

**Comment by Cupcak3** [comment]
Hi there. Sorry for coming back to this issue after a long time. I assume you use the Chinese client and executable. [V1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease) adds support for the Chinese client. However, the game's language still needs to be set to English. Please let us know if your issue has been resolved so that we may close this issue. Thanks!
