### ISSUE TITLE
Character Scanners stops on Kokomi

### ISSUE THREAD

**Issue by BlackClaude** [Andrewthe13th/Inventory_Kamera#133]
I have ran the scanner twice already and it keeps stopping on kokomi.

**Comment by Lowallyn** [comment]
I don't think it stops at kokomi, i've ran this version of the genshin scanner twice and it stops at either 16/17 characters of the 32 or so characters that I have.

**Comment by misugashi** [comment]
nah it stops on kokomi specifically, happens for me too

**Comment by Lowallyn** [comment]
> nah it stops on kokomi specifically, happens for me too

I don't have kokomi so that can't be the case for me then.

**Comment by TheBigSoda** [comment]
Also stops at Kokomi for me. At first, she was the top character of my list so I thought maybe it was an issue with it wrapping back around after reaching the end of the list. Moved her location, same issue. Set her as my active character so that it'd start with her, and it locked immediately.

Error Log:
Could not determine character's name or element
Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
This is a known bug and we have a fix written for it. You may click to the next character when it hangs on Kokomi or any other character with a long name and it will be fine, it just won't scan that character.

**Comment by dunia01** [comment]
For me is stopping on Electro Traveler (M). Is there a correlation? Also, I think it's stopping after checking the first talent of any character if Childe is on the Active Party.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
