### ISSUE TITLE
Artifacts scan gets wrong results

### ISSUE THREAD

**Issue by burekitas** [Andrewthe13th/Inventory_Kamera#134]
hey, something goes wrong with artifact scanning. some artifacts just got completely wrong resaults. in this picture for instance - my zhongli have a TOTM flower and WT goblet. also, gambler's and berserker cant be 5*. and I got the flower string from the jason - it's missing a substat.
{"setKey":"Gambler","slotKey":"flower","rarity":5,"mainStatKey":"hp","level":20,"substats":[{"key":null,"value":0.0},{"key":"hp_","value":4.1},{"key":"def","value":19.0},{"key":"enerRech_","value":25.9}],"location":"Zhongli","lock":false,"SubStatsCount":4,"Id":8}

![image](https://user-images.githubusercontent.com/81911369/147408870-25d9846d-b6ed-4d41-96cf-1080cbd15921.png)

from a brief scan of the rest in genshin optimizer I think that's all it got wrong but I'm not a 100% sure

ps - this tools doesn't read mora?

thanks

**Comment by ShatteredGod** [comment]
![fhghfkmdgh](https://user-images.githubusercontent.com/71801833/147410536-a9af153f-fb63-4018-8450-ac95688ac0a1.png)
I'M SO SORRY, i'll delete it later. but nice~
had to do it.

**Comment by Cupcak3** [comment]
Thanks for the report. Unfortunately this is a tricky thing to assess and catch problems at run time. Text recognition of the sub-stats and artifact set name are the trickiest because of the green text that the artifact name uses. We're working on ways to improve scanning accurate artifact sets, which should also improve the accuracy of missing sub stats.

The tool also doesn't scan mora yet. We will add that in.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

The scanner also now scans mora when scanning materials.

**Comment by burekitas** [comment]
I believe 1.2 solved this problem so I'll close it. but it did fail to parse the mora amount
