### ISSUE TITLE
Scanner reading some artifacts as Adventurer Set

### ISSUE THREAD

**Issue by Galaith** [Andrewthe13th/Inventory_Kamera#149]
Was working fine before, but some of my artifacts are being listed as a 5* Adventurer Set

![adventurer](https://user-images.githubusercontent.com/96900030/147803477-5ec6ef64-8f00-46a2-9e60-b8ec103b8f95.png)

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

On a side note, do you know if the artifacts that caused this were Noblesse Oblige or Wanderer's Troupe artifacts?
