### ISSUE TITLE
Scanned image is offset

### ISSUE THREAD

**Issue by afrasso** [Andrewthe13th/Inventory_Kamera#192]
First, thank you for working on this program. I've used it before without issues, and it's great for artifact analysis. :)

When I downloaded the latest release (1.2), when I scan my artifacts the screenshot is offset (see the attached screenshot I grabbed from the logging/artifacts folder):
![artifact0](https://user-images.githubusercontent.com/3944808/151676169-505feab2-0a8e-45c0-a1ab-f543d01add40.png)

I currently have my resolution set to 1920x1080, but I tried a bunch of the different resolutions, and all seemed to have the same problem.

Any ideas?

**Comment by afrasso** [comment]
Update: I completely closed out GI and restarted it, and that seems to have fixed the issue. Not sure why. I usually play on a widescreen monitor with a resolution of 3440x1440, so many that has something to do with it.

**Comment by afrasso** [comment]
I can confirm I can reproduce the issue again by going back to 3440x1400 fullscreen, exiting out of GI, reopening it, and setting the resolution to 1920x1080. Something about changing the resolution while in-game is different than if you start up the game with that resolution (things are slightly shifted around).

**Comment by Cupcak3** [comment]
There is a specific behavior with Genshin and ultrawide resolutions. Issue #40 figured it out that the UI on ultrawide is compressed slightly. Changing resolutions in Genshin keeps this compressed UI until a restart. We can probably adjust screen region capturing but it's low priority for now since a reliable fix is known. I'll add something about this to the readme
