### ISSUE TITLE
Crash when scanning Dark Iron Sword

### ISSUE THREAD

**Issue by Drakenwoo** [Andrewthe13th/Inventory_Kamera#202]
Hello !

Could you please fix the fact that the application crashes when analyzing the Weapon "Dark Iron Sword" : 
https://genshin-impact.fandom.com/wiki/Dark_Iron_Sword

Thank you !

**Comment by Cupcak3** [comment]
Weird, I wouldn't expect it to crash at all for any weapon (obviously). Is it a hard crash or are there any error messages in the log?

**Comment by Drakenwoo** [comment]
the software simply stops the scan at this weapon everytime

**Comment by Cupcak3** [comment]
So there is no error log whatsoever? Does the application close or does it stay open? If it stays open there should be some sort of log in the window of anything that aborts a scan.

**Comment by Drakenwoo** [comment]
it doesn't make sense, I tried to do the scan for several times without success, and today it worked without interruption, really weird, so I think the problem is solved now x) Sorry for the inconvenience

**Comment by Cupcak3** [comment]
Very strange indeed. It's the only inconvenience is when something suddenly decides to work 😅

By chance, do you think the scanner was getting to the enhancement ores at the end of your inventory by chance? Some users reported those causing issues and crashes. If so, then that has hopefully been fixed in the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease). 

I am going to close this issue since you've said the problem has gone away. Should it come up again please feel free to reopen this issue or to open a new issue.
