### ISSUE TITLE
Scanner Won't Open

### ISSUE THREAD

**Issue by goldeagle6500** [Andrewthe13th/Inventory_Kamera#224]
![Screenshot_21](https://user-images.githubusercontent.com/96553884/154782917-d3aa112a-5ae4-4a42-a25c-a523cdf30974.png)

Windows says I don't have access to the files or something... can't open the scanner (check screenshot)

**Comment by Cupcak3** [comment]
This error could be happening because Kamera requires admin permissions. Please try the troubleshooting steps in [this link](https://support.microsoft.com/en-us/topic/-windows-cannot-access-the-specified-device-path-or-file-error-when-you-try-to-install-update-or-start-a-program-or-file-46361133-47ed-6967-c13e-e75d3cc29657) and let me know if you could resolve the problem.
