### ISSUE TITLE
character scan not working, goes to character page and stucks

### ISSUE THREAD

**Issue by ranehal** [Andrewthe13th/Inventory_Kamera#261]

**Comment by Luvideria** [comment]
Similar issue here.

It seems the problem was the use of my UltraWide monitor. I tried again on my laptop screen and it worked after rebooting both the game and Kamera.

So, one workaround could be to set the OS resolution to a typical 16:9 resolution for the time of the procedure.
This, of course, waiting for the issue to be fixed

Below is the description of the problem in more details

---

Successfully recorded all my weapons, so it can work, but I noticed the images were off by a bit.

What I did:
- check the "characters" in kamera
- 50ms delay
- screen in 1920x1080, also tried with 1920x1200, also tried with 1900x600
- genshin window in the middle of the screen
- open paimon menu
- press start

What happened:
- exit paimon menu
- enter character menu
- kamera records the name of my character and its element / level incorrectly:
```
Name: Xingqiu
Element: Geo
Level: 79 / 800
Constellation: 6
```
While Xingqiu is of course Hydro, and the level is not out of 800, also I have only C2
- mouse cursor moved to "attribute" section of the left side menu
- mouse cursor moved to constellation menu
- mouse cursor clicks successively on all constellations BUT NOT the last one
- leaves the character menu, returning in game
- Kamera records talents but it takes pictures of the in game background and records "1,1,1"
- opens paimon menu and tries to change the avatar

**Comment by Cupcak3** [comment]
Hi there, please see #40 about ultrawide mode. Currently there's no plans to do work around ultrawide's UI as this workaround is effective enough.
