### ISSUE TITLE
[BUG] Tartaglia's passive causes normal attack talent level to be misreported

### ISSUE THREAD

**Issue by briankchan** [Andrewthe13th/Inventory_Kamera#279]
Tartaglia's passive talent Master of Weaponry raises his party members' normal attack talent level by 1, causing the scanner to report their talent levels 1 too high.

## **How to reproduce**
Scenario 1: Scan Characters without Tartaglia in the active party (and on an account that has Tartaglia).

Scenario 2: Scan Characters with Tartaglia in the active party.

## **Expected behavior**
Scenario 1: Tartaglia's normal attack talent level should be reported correctly. (Instead, it is reported to be 1 higher than it actually is.)

Scenario 2: All party members' normal attack talents should be reported correctly. (Instead, they are all reported to be 1 higher than they actually are.)
 
## **Checklist before sending issue**
Check the tickbox by replacing [ ] with [x] (in editor) or tick it after leaving the Text Editor:
- [x] I am using the latest version of Inventory Kamera or/and have clicked Update Lookup Tables to update the database.
- [x] I am using *English* as a game language
- [x] I am using the 16:9 or 16:10 window screen and leave the screen in the Paimon menu before starting the application.
- [ ] I tried setting the delay to maximum and still experiencing issues. (I really don't think this will help)
- [x] I have correctly set my character and inventory keys in Inventory Kamera
- [x] I do NOT have any image filtering softwares enabled for Genshin (HDR, Image Sharpening, etc.)

**Comment by Cupcak3** [comment]
Thanks for bringing this to my attention. I don't have Tartaglia so I wasn't even aware of that passive let alone the edge case of him being in the party. I guess a fix would be to *not* have him in your party when scanning in the meantime. I'll write something to handle this.

**Comment by kel-z** [comment]
Scenario 1 is still being misreported. Latest fix only accounts for when Tartaglia is in the party, which addresses Scenario 2.

![image](https://user-images.githubusercontent.com/24833484/172701052-e696eb26-23a9-4a3b-92d6-d4bd4111a454.png)
Pictured: Tartaglia is not in the on-field party, but his passive is still active when viewing talent screen.

Expected normal attack level is 5, but it is actually being misreported as 6 still.

**Comment by Cupcak3** [comment]
Can you confirm that my understanding of Tartaglia's passive is correct?

1) With ascension 4 (alive or dead) Tartaglia in on-field party, ONLY on-field party members have +1 to their auto attack
2) With ascension 4 Tartaglia NOT in on-field party, NO characters have +1 to their auto attack
3) With ascension 1,2,3 Tartaglia, NO characters have +1 to their auto attack

**Comment by briankchan** [comment]
> 2\. With ascension 4 Tartaglia NOT in on-field party, NO characters have +1 to their auto attack

This part is incorrect. When Tartaglia is not in the active party (and is at ascension 4 or higher), the character menu displays his normal attack with the +1, as shown in @kel-z's screenshot above.

**Comment by mokahless** [comment]
Tacking on this due to 323 being closed. I was also noticing every normal talent of every one of my characters was -1.

Alternative dirtier suggestion of how to address this instead of figuring out all the tartaglia situations: Detect the colour of the talent level number. If not the normal colour, it indicates it is boosted. Otherwise, it isn't. Since Tartaglia is currently the only one to be able to increase (or decrease) normal attack talent, and only by one, this should work until hoyo adds another method to boost normal talents. The colour is the same as the con boosts for C3 and C5.
![image](https://user-images.githubusercontent.com/30379366/181805965-a7cf4cda-a3ad-4228-a8f6-30617f1428be.png)
![image](https://user-images.githubusercontent.com/30379366/181807684-b87b1ed8-ebe0-421d-874b-969fdb2312ab.png)


There is also available a project called grasscutter on github. It attempts a private server for genshin. While in early alpha and heavily featureless, everything you would need to test this yourself for the Inventory Kamera works.

In the meantime, if you don't have time to figure out a good fix, I would request reverting the change of addressing tartaglia in the first place. As an end-user, it is much easier to simply make sure he's not in my party before scanning than it is to manually +1 to each normal talent for all my characters after.

**Comment by Cupcak3** [comment]
@mokahless there is a pull request that addresses Tartaglia's shenanigans. I just haven't had the time to do all that's necessary to get that into a release yet. I hope to be able to find time this weekend to do some bug fixing and get a release out.
