### ISSUE TITLE
[BUG] Application Settings Reset on Directory Change

### ISSUE THREAD

**Issue by b4lesh** [Andrewthe13th/Inventory_Kamera#301]
## Problem
If I change name of directory Inventory_Kamera - my settings will reset. I think this is a problem because the app use absolute path, not a relative. Fix this, please (* ^ ω ^)

**Comment by Cupcak3** [comment]
Hi there. Sorry for the late reply. I've looked into this issue to see what can be done and I do not believe a simple fix is possible. 

The short story: A custom settings manager is needed to fix this. I can think about it but it's a bit out of the way.

The long story: Any setting changes (and only settings NOT saved as the default) are saved off to some folder in AppData. The application automatically (.NET automatically) tries to find this custom settings config found using a special calculation based on the .exe's directory. So if the directory changes... then that new calculation result changes and it (probably) won't find old custom settings. So everything is loaded as default. .NET's calculation can't be overridden for security reasons but it can be forced if the application were compiled with a certain setting enabled. However this setting cannot be enabled because it requires admin privileges... a bit of a catch-22. Thus a custom settings manager is necessary.

**Comment by Cupcak3** [comment]
Support for permanent settings added with [V1.3.0](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.0) release
