### ISSUE TITLE
[BUG] Artifact scanning stopping before complete scan

### ISSUE THREAD

**Issue by Natsume1986** [Andrewthe13th/Inventory_Kamera#328]
Hi!!!! I have a bug / problem here

It keeps crashing against the scan. always in the same place What is the traffic there or am I doing something wrong?

[https://youtu.be/iaANS2xlJ8g](url)

**Comment by b4lesh** [comment]
Hello. You use old version of the app. Use new version 1.2.7

**Comment by Natsume1986** [comment]
Same Error with 1.2.7

[URL=https://bilderupload.org/bild/215a13998-bild-2022-07-20-124636305][IMG]https://bilderupload.org/image/thumbnail/resized-215a13998-bild-2022-07-20-124636305.png[/IMG][/URL]

**Comment by Faahm** [comment]
Can confirm that I also have this problem. The scanner crashes when I reach the 3-4 row while scanning and I'm using the latest version as of writing this comment.

**Comment by Cupcak3** [comment]
Hi there, please attach one or both of the logs generated from an execution where this happens. I can't see any issue with your setup but it consistently stops on the same artifact. Please enable the "log all screenshots" button and do a scan. If this issue occurs, zip up the last artifact folder from the scan in `logging\artifacts`, and upload the zip so that I may see if something about the artifact is messing up the scan.

**Comment by Cupcak3** [comment]
I am going to close this issue because the requested information has not been provided. Feel free to reopen this issue.
