### ISSUE TITLE
[BUG] after scanning X amount of items, scanner will change tasks or interrupt (+ incorrect scanned quantities)

### ISSUE THREAD

**Issue by TheSast** [Andrewthe13th/Inventory_Kamera#377]
### Current Behavior

After scanning a certain amount of items the software will simply swap to the next scan task (eg. scans only a few artifacts then goes to scan materials), this most commonly happends in the material section, where I have failed to have a successful full scan of all my meterials.
_Sometimes_ I also get this Error:
![image](https://user-images.githubusercontent.com/27977196/188827690-6495ee1d-94d8-4f3e-920c-c235457df5ee.png)
The quantities shown in the export files are also incorrect.

### Expected Behavior

The scanner to not skip rows or items

### Reproducing a Behavior

I have no idea how to reproduce the behaviour, and I am unable to include a screen recording since a new issue has risen which I will report shortly.
I am able to provide an export file (inside a zip left in the evidence section) of one of my attempts which resulted in the previously mentioned error.

### Device OS

Windows 10

### Genshin Impact Version

3.0.0

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1920x1080, windowed

### Evidence

![image](https://user-images.githubusercontent.com/27977196/188827690-6495ee1d-94d8-4f3e-920c-c235457df5ee.png)

[genshinData_GOOD_2022_09_07_10_11.zip](https://github.com/Andrewthe13th/Inventory_Kamera/files/9504274/genshinData_GOOD_2022_09_07_10_11.zip)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by PraxisPrime** [comment]
Reporting the same problem....seems to happen in the materials section.   Everything is going fine then exits out part way through and then tries to continue on the same section.  Artifact scanning was fine though...just materials.  Noted on this ticket since the issue seems to be similar/same.  PC capture at 2K

Error Log:

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
 at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)
at InventoryKamera.InventoryKamera.GatherData()
Could not determine Jean's level. Setting to 1.
Failed to parse quantity for TuskOfMonocerosCaeli
Sequence contains no elements
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)
at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)
 at InventoryKamera.InventoryKamera.GatherData()
Sequence contains no elements
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
 at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)
 at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)
 at InventoryKamera.InventoryKamera.GatherData()

**Comment by alhyastarain** [comment]
I have the same issue. The game finishes reading my characters, then gets out and does this, by order:
-Open and close Paimon menu
-Pause
-Do normal attacks (clicking with mouse)
-Open and close Paimon menu a few times
-Click again and zoom in (scroll up)
-Stop the scan
This has happened twice. I will record and run it again a third time, and if it happens again, I'll publicate my error.

**Comment by Cupcak3** [comment]
This issue is quite old. Please let me know if this still exists on recent versions
