### ISSUE TITLE
Scanner loops infinitely on characters

### ISSUE THREAD

**Issue by GH-Ben** [Andrewthe13th/Inventory_Kamera#422]
### Current Behavior

When scanning characters, after reaching the last character in the list, the scanner will loop back around to the first one and start scanning everything again. I let it run for a while but decided to stop it once it reached 632 characters scanned. Reproduced both on fast, slower and slow speeds.

### Expected Behavior

The scanner stops scanning

### Reproducing a Behavior

Start a scan with the character scan option selected

### Device OS

Windows 10

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.6

### Screen resolution, screen mode, and UI scale

3840x2160 (fullscreen) and 2560x1400 (windowed)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by aelfwyne** [comment]
Came here for the same issue.

**Comment by Tron-Creeper2** [comment]
Yop, got the same issue..

**Current Behavior**
When scanning characters, after reaching the last character in the list, the scanner will loop back around to the first one and start scanning everything again. I let it run for a while but decided to stop it once it reached 319 characters scanned.
Reproduced on fast (so far)

**Expected Behavior**
The scanner stops scanning

**Reproducing a Behavior**
Start a scan with the character scan option selected

**Device OS**
Windows 11

**Genshin Impact Version**
3.4

**Inventory Kamera Version**
1.3.7

**Screen resolution, screen mode, and UI scale**
2560x1440 (fullscreen) and 1920x1080 (windowed)

**Additional notes and remarks**
No response

**Evidence**
No response

**Preflight Checklist**

- [☑️]  I have checked for similar issues in the issue page, and I have found similar to mine.
- [☑️]  I am using the latest version of the scanner.
- [ ]  I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ]  I have attached the video recording to the bug report.
- [☑️]  I have attached the error log to the [bug report](https://drive.google.com/drive/folders/1WF6RehpC3rcaeZFX8SdwLexDAj78V290?usp=sharing).
- [❔]  I am available to later explains the issue.
- [☑️]  I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [☑️]  I use default in-game keybindings or have configured keybindings for the scanner.
