### ISSUE TITLE
weapons and artifacts not assigned properly

### ISSUE THREAD

**Issue by Vergil1550** [Andrewthe13th/Inventory_Kamera#468]
### Cause of the issue

Missing game information or instruction

### Describe your issue

![Screenshot (8)](https://github.com/Andrewthe13th/Inventory_Kamera/assets/115262731/a57050a9-9e0e-4431-82e6-94edcc7ca635)

when I opened webpage and updates my database my characters have missing artifacts and some characters have been wrongly assigned to 1* weapons

### How can we fix this?

I am waiting for the community's explanation, I am waiting for the developer(s) to help

### Additional notes and remarks

this problem occurred after I updated optimizer to 3.10

### Preflight Checklist

- [X] I understand that this is not a feature request or enhancement request. Such request is done in the Discussions tab.
- [X] I understand that this is not a question, a crash report, an error report, or a bug report. Such request is done using Bug Report in the Issue tab.
- [X] I am available for further questions.
- [X] I can help with documentation.
- [X] I understand the scanner's codebase.
- [X] I have checked the Issues tab and Discussions tab, and there are none similar to mine.

**Comment by baybolll** [comment]
Hi, I was using the program before. I tried it yesterday. I got this error, some of my artifacts are not showing up. 
![image](https://github.com/Andrewthe13th/Inventory_Kamera/assets/143804109/bd0327de-248e-4f36-a963-b99ddbc0607a)
How to fix the problem.

**Comment by trashpanda-007** [comment]
Can confirm, I am also having the issue of artficacts and weapons not being assigned properly after updating to 3.10

**Comment by lunarmint** [comment]
Same here, got this problem on Tighnari who uses a Scion of the Blazing Sun bow with Wanderer's Troupe set. Could not read the bow, the flower, and the feather.

**Comment by HelpSeeker** [comment]
Same. 35 out of my 54 characters are missing at least one assigned artifact. Some fully geared characters didn't even have a single artifact according to the scanner.
Redoing the scan with 1.3.9 resolved those issues.

**Comment by baybolll** [comment]
hi can someone send me a link to version 1.3.9, do the new Artifacts in this version work correctly?

**Comment by BlackHazel** [comment]
Same here, v1.3.10 is missing tons of artifact & weapon, while 1.3.9 is working perfectly.
![1 3 10 vs 1 3 9](https://github.com/Andrewthe13th/Inventory_Kamera/assets/12218001/53b3975d-86c5-4e99-b919-00a3d9329a38)

Also since 1.3.10 the scanner is skipping lines due to not aligning the artifact properly, we can see on this screen that there is a few pixels from the preview row which make the scanner skips the first & last line, which basically make him scan 3/5 row per page.
In some other case, he also scans the last row from the preview page, skip the first row, scan the row 2/3/4, and skip the last row.
This never happened before and I've been using this scanner since v1.2.2 (February 2022).
![1 3 10_scanning](https://github.com/Andrewthe13th/Inventory_Kamera/assets/12218001/7cad00d3-c903-4e92-9a19-114862d54957)

I also tested with a lower speed, but even with the delay set to slow the problem of alignment is still screwing the scans.

For those who have the problem and need to rollback for the time being, you can skill download the v1.3.9 there: https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.3.9

1) Ignore the new update (the time that a new version is released with a fix).
2) Update the tables.
3) Use it as you use it normally.

![rollback](https://github.com/Andrewthe13th/Inventory_Kamera/assets/12218001/e12fc091-8693-4019-8017-245a93611928)

**Comment by Cupcak3** [comment]
This should be fixed in the latest release. Please reopen the issue if you find the error still exists
