### ISSUE TITLE
Error: emperorsbalsam is not a valid Character Development Item Name

### ISSUE THREAD

**Issue by neyi780** [Andrewthe13th/Inventory_Kamera#88]
I have some emperor balsams i can't use

![image](https://user-images.githubusercontent.com/65132648/144871014-12911009-c9fd-4353-a595-a7272a10e152.png)

and it gives an error and it skips 2 lines, and exits the char dev items tab, i'm probably sure it will give an error with the Alkahest too.

**Comment by Andrewthe13th** [comment]
Thanks for the report. Will try to add those items in.

**Comment by Cupcak3** [comment]
This is a very old issue and has been fixed by the latest release or prerelease so I am going to close it. Additionally, semi-automatic updating for new versions of Genshin have been made available under the `options` tab. If you would like to update these lists manually you can do so in their respective files in the `inventorylists` folder. Documentation is coming to explain formatting if you choose to update IK with new data this way and are a little lost. This ***does not*** update IK itself.
