### ISSUE TITLE
inventory error - Inventory Kamera

### ISSUE THREAD

**Issue by PedroDozze** [Andrewthe13th/Inventory_Kamera#97]
It really is a very useful application and I'm loving to use it, but there was an error and I'd like to report it here.

I had the event item "Emperor's Balsam" in my inventory to level the sword of the respective event, when the app read the item it simply scrolled down and counted from the fifth line, so I could solve the problem. I want to level the sword earlier than I was planning and as soon as that item left my inventory the app read normally.

![image](https://user-images.githubusercontent.com/96024522/145729464-bfecdd03-73b3-4edf-aa26-6d5bf1cb4b76.png)

Possible solution suggestion: Make the application read and save all items regardless of whether they "exist" yes or no, and then make the provider that will read the items (In my case Seelie.me) check with the registered items or available on the website.

Thank you in advance for creating the app!

**Comment by Cupcak3** [comment]
Event items haven't been a priority since they're finite and usually expected to be consumed once you get them. Though I agree it shouldn't "halt" scanning the rest of your inventory. I am currently working on a solution that works towards fixing this behavior. This won't get rid of the need to "know" that an item exists, but rather it will take away the need for manually hardcoding new weapons/artifacts/items, etc., for the scanner each update. I can try to get this out tomorrow.

On the technical side, Seelie's formatting for material keys is a bit hard to replicate algorithmically as it can be a bit arbitrary. To see what I mean you can take a look on how they distinguish the two different "chaos part" material sets. Thankfully Seelie.me is working on an import method that accepts GOOD which uses keys that can be reliably generated from item names.

**Comment by Cupcak3** [comment]
This is an old issue and has been fixed by the latest release or prerelease so I am going to close it. Additionally, semi-automatic updating for new versions of Genshin have been made available under the `options` tab. If you would like to update these lists manually you can do so in their respective files in the `inventorylists` folder. Documentation is coming to explain formatting if you choose to update IK with new data this way and are a little lost. This ***does not*** update IK itself.
